/***************************************************************************/
/*
 *   Author:  Gary Williams
 *   Made safe for uclibc
 *
 */
#include "defs.h"

void version_info()
{
   printf("GTD:  Version 1.0\n");
   printf("        *   Copyright (c) 2002 Gary Williams\n");
   printf("        *   Lee, MA  01238\n");
   printf("\n\n");
   fflush(stdout);
   return;
}

void commandLineError()
{

   printf("Usage:  gtd -i <input_file> -o <results_file> -C <number>\n");
   printf("            -T <default_timeout> -t <run_time> -r <repeat_cnt>\n");
   printf("            -n -k -R -D <directory>\n\n");

   printf("All options except the -i option are optional.  -i must be specified.\n\n");

   printf("   -i <input_file>     :  file is a list of test command lines\n");
   printf("      default:  none, you must supply a test list (suffix = .gtd)\n");
   printf("   -D <directory>      :  User specified run directory\n");
   printf("      default:  The current directory\n");
   printf("   -o <results_file>   :  file is where result should go\n");
   printf("      default:  RESULTS\n");
   printf("   -x <results_xml_file>   :  file is where XML result should go\n");
   printf("      default:  RUNTESTS.xml\n");
   printf("   -C <number>         :  number is the quantity of test running at all times\n");
   printf("      default:  1, MAX=32\n");
   printf("   -T <default_timeout>:  How long a test should run before begin killed\n");
   printf("      default:  28800 seconds (8 hours)\n");
   printf("   -t <run_time>       :  How long should this driver run\n");
   printf("      default:  one complete pass through the test list\n");
   printf("   -r <repeat_cnt>     :  How many time should a given test be run in a row\n");
   printf("      default:  1\n");
   printf("   -n                  :  All tests run in new session\n");
   printf("      default:  no\n");
   printf("   -k                  :  Keep ALL test results\n");
   printf("      default:  dispose of passing results\n");
   printf("   -R                  :  Randomize test list\n");
   printf("      default:  run list in order given\n");
   printf("   -a                  :  Put all results in results file\n");
   printf("      default:  ignore results for unsupported or tests not found\n\n");

   printf("Generated Files:\n");
   printf("   RESULTS             :  List of test results (unless changed, above)\n");
   printf("   RUNTESTS.xml        :  List of completed tests in XML format\n");
   printf("   FAILURES            :  Command lines of the failed tests\n");
   printf("   DRVLSxxx            :  Generated if the -R option is specified\n");
   printf("                          xxx is generated by tempnam().  A new file\n");
   printf("                          is generated for each pass through the list\n");
   printf("                          and the old file is destroyed.\n\n");

   printf("Generated Directories:\n");
   printf("   GTD_<pid>           :  Directory which gtd moves into to run tests\n");
   printf("   <test_name>         :  A directory named after the test is created\n");
   printf("                          for each test to run in.  This directory and\n");
   printf("                          its contents are destroyed for passing tests\n");
   printf("                          unless -k is specified\n\n");

   exit(1);
}
